### ISSUE TITLE
Uploading the keytab file

### ISSUE THREAD

**Issue by elusiveity** [walkamongus/realmd#1]
Howdy

When declaring the keytab file, what's the officially supported method of pushing it to the agent? I've attempted to use file {} in our site.pp however it creates a conflict. 

At the moment we're looking at hacking in the source=> part of the file{'krb_keytab'} in join/keytab.pp however I would like to know the official method of using the keytab file

Thanks

**Comment by walkamongus** [comment]
Hello,

Currently the module expects the keytab to be deployed via some out-of-band method (not Puppet).

If you really want to deploy the keytab via Puppet, I think a good way to do that would be to add a parameter called something like 'krb_keytab_source' or 'krb_keytab_content' and initialize it to undef.

Then you could add any validations in init.pp and pass the value down into the realmd::join::keytab class for the source and/or content for the  File['krb_keytab'] resource. Does that help?

Feel free to submit a PR if you put together something that you think others might find useful and thanks for checking out the module!
