### ISSUE TITLE
realmd dependencies not installing from module

### ISSUE THREAD

**Issue by nrmjba** [walkamongus/realmd#12]
### EDIT:

**It looks like it is actually only missing `samba-common-tools`**

**All of the other packages installed correctly. Looking at the module `samba-common-tools` is not part of the install process**

**Not sure if that is by design or not but it is a required package for realmd on CENTOS 7**

I install the module and set the join name and password as well as the domain. When i run the puppet agent I get an error that the join failed due to realmd not having dependencies installed.

I've included the error message, my current manifest, and the output of facter below

### ERROR:
<pre>Notice: /Stage[main]/Realmd::Join::Password/Exec[realm_join_with_password]/returns: realm:
Couldn't join realm: Necessary packages are not installed:
oddjob, oddjob-mkhomedir, sssd, samba-common-tools
</pre>
### CONFIG:
<pre>class {'::realmd':
  domain => '<removed>',
  domain_join_user => '<removed>',
  domain_join_password => '<removed>',
  manage_sssd_config => true,
  sssd_config => {
    'sssd'=> {
      'domains'=> '<removed>',
      'config_file_version'=> '2',
      'services'=> 'nss,pam',
     },
    "domain/<removed>"=> {
      'ad_domain'=> '<removed>',
      'krb5_realm'=> '<removed>',
      'realmd_tags'=> 'manages-system joined-with-adcli',
      'cache_credentials'=> 'True',
      'id_provider'=> 'ad',
      'access_provider'=> 'ad',
      'krb5_store_password_if_offline'=> 'True',
      'default_shell'=> '/bin/bash',
      'ldap_id_mapping'=> 'True',
      'fallback_homedir'=> '/home/%u',
      'krb5_store_password_if_offline'=> true,
      'use_fully_qualified_names'=> false,
      'access_provider'=> 'simple',
      'simple_allow_groups'=> '<group names removed>',
     },
   },
 },</pre>

### System information:
<pre>
CentOS Linux release 7.3.1611 (Core)
aio_agent_version => 1.5.2
augeas => {
  version => "1.4.0"
}
disks => {
  fd0 => {
    size => "4.00 KiB",
    size_bytes => 4096
  },
  sda => {
    model => "Virtual disk",
    size => "30.00 GiB",
    size_bytes => 32212254720,
    vendor => "VMware"
  }
}
dmi => {
  bios => {
    release_date => "07/30/2013",
    vendor => "Phoenix Technologies LTD",
    version => "6.00"
  },
  board => {
    manufacturer => "Intel Corporation",
    product => "440BX Desktop Reference Platform",
    serial_number => "None"
  },
  chassis => {
    asset_tag => "No Asset Tag",
    type => "Other"
  },
  manufacturer => "VMware, Inc.",
  product => {
    name => "VMware Virtual Platform",
    serial_number => "VMware-42 27 4b a6 68 04 0b 30-0d 52 e1 2c f3 d5 dc c0",
    uuid => "42274BA6-6804-0B30-0D52-E12CF3D5DCC0"
  }
}
facterversion => 3.2.0
filesystems => xfs
identity => {
  gid => 0,
  group => "root",
  uid => 0,
  user => "root"
}
is_virtual => true
kernel => Linux
kernelmajversion => 3.10
kernelrelease => 3.10.0-327.el7.x86_64
kernelversion => 3.10.0
load_averages => {
  15m => 0.05,
  1m => 0,
  5m => 0.01
}
memory => {
  swap => {
    available => "2.00 GiB",
    available_bytes => 2147479552,
    capacity => "0%",
    total => "2.00 GiB",
    total_bytes => 2147479552,
    used => "0 bytes",
    used_bytes => 0
  },
  system => {
    available => "3.30 GiB",
    available_bytes => 3539267584,
    capacity => "10.98%",
    total => "3.70 GiB",
    total_bytes => 3975888896,
    used => "416.39 MiB",
    used_bytes => 436621312
  }
}
mountpoints => {
  / => {
    available => "25.99 GiB",
    available_bytes => 27906772992,
    capacity => "5.32%",
    device => "/dev/mapper/centos-root",
    filesystem => "xfs",
    options => [
      "rw",
      "seclabel",
      "relatime",
      "attr2",
      "inode64",
      "noquota"
    ],
    size => "27.45 GiB",
    size_bytes => 29475753984,
    used => "1.46 GiB",
    used_bytes => 1568980992
  },
  /boot => {
    available => "345.68 MiB",
    available_bytes => 362475520,
    capacity => "30.40%",
    device => "/dev/sda1",
    filesystem => "xfs",
    options => [
      "rw",
      "seclabel",
      "relatime",
      "attr2",
      "inode64",
      "noquota"
    ],
    size => "496.67 MiB",
    size_bytes => 520794112,
    used => "150.98 MiB",
    used_bytes => 158318592
  }
}
networking => {
  dhcp => "<removed>",
  domain => "<removed>",
  fqdn => "<removed>",
  hostname => "<removed>",
  interfaces => {
    eno16780032 => {
      bindings => [
        {
          address => "10.5.42.35",
          netmask => "255.255.0.0",
          network => "10.5.0.0"
        }
      ],
      bindings6 => [
        {
          address => "fe80::250:56ff:fea7:7397",
          netmask => "ffff:ffff:ffff:ffff::",
          network => "fe80::"
        }
      ],
      dhcp => "<removed>",
      ip => "<removed>",
      ip6 => "<removed>",
      mac => "<removed>",
      mtu => 1500,
      netmask => "255.255.0.0",
      netmask6 => "ffff:ffff:ffff:ffff::",
      network => "<removed>",
      network6 => "fe80::"
    },
    eno33559296 => {
      mac => "<removed>",
      mtu => 1500
    },
    lo => {
      bindings => [
        {
          address => "127.0.0.1",
          netmask => "255.0.0.0",
          network => "127.0.0.0"
        }
      ],
      bindings6 => [
        {
          address => "::1",
          netmask => "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
          network => "::1"
        }
      ],
      ip => "127.0.0.1",
      ip6 => "::1",
      mtu => 65536,
      netmask => "255.0.0.0",
      netmask6 => "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
      network => "127.0.0.0",
      network6 => "::1"
    }
  },
  ip => "<removed>",
  ip6 => "<removed>",
  mac => "<removed>",
  mtu => 1500,
  netmask => "255.255.0.0",
  netmask6 => "ffff:ffff:ffff:ffff::",
  network => "<removed>",
  network6 => "fe80::",
  primary => "eno16780032"
}
os => {
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.3.1611",
    major => "7",
    minor => "3"
  },
  selinux => {
    config_mode => "enforcing",
    current_mode => "enforcing",
    enabled => true,
    enforced => true,
    policy_version => "28"
  }
}
partitions => {
  /dev/mapper/centos-root => {
    filesystem => "xfs",
    mount => "/",
    size => "27.46 GiB",
    size_bytes => 29490151424,
    uuid => "3b077c96-8dd7-4960-9967-adba4762dc27"
  },
  /dev/mapper/centos-swap => {
    filesystem => "swap",
    size => "2.00 GiB",
    size_bytes => 2147483648,
    uuid => "8b1d480f-b0ea-4ee8-a1d9-089f6a286750"
  },
  /dev/sda1 => {
    filesystem => "xfs",
    mount => "/boot",
    size => "500.00 MiB",
    size_bytes => 524288000,
    uuid => "c4edd4a3-a0b2-48ed-ac2b-0370d07c6fc0"
  },
  /dev/sda2 => {
    filesystem => "LVM2_member",
    size => "29.51 GiB",
    size_bytes => 31686918144,
    uuid => "GlZjhC-5Bbp-djjA-XAO0-3WFD-qubn-nuuTRa"
  }
}
path => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
processors => {
  count => 2,
  isa => "x86_64",
  models => [
    "Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz",
    "Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz"
  ],
  physicalcount => 1
}
ruby => {
  platform => "x86_64-linux",
  sitedir => "/opt/puppetlabs/puppet/lib/ruby/site_ruby/2.1.0",
  version => "2.1.9"
}
system_uptime => {
  days => 0,
  hours => 4,
  seconds => 15107,
  uptime => "4:11 hours"
}
timezone => EST
virtual => vmware
</pre>

**Comment by walkamongus** [comment]
releases 1.0.0 and 2.0.0 should fix this issue

**Comment by rsynnest** [comment]
I'm getting similar errors on Ubuntu 16.04 using `walkamongus/realmd v2.0.0` 
realmd states that "Necessary packages are not installed: sssd-tools sssd libnss-sss libpam-sss adcli", even after I've verified that all packages are installed.
The error is most likely being caused by a possible bug in aptd as described [here](https://bugs.launchpad.net/aptdaemon/+bug/1319454) and [here](https://bugs.launchpad.net/ubuntu/+source/realmd/+bug/1333694).
A very simple fix is to install packagekit, which realmd uses for dependency management. Packagekit accurately finds installed packages and the realm is joined successfully.
