### ISSUE TITLE
Could not retrieve catalog: undefined method 'ref' for nil:NilClass

### ISSUE THREAD

**Issue by unixsanet** [walkamongus/realmd#15]
I'm trying to get this module working with RHEL7, specifically using Satellite 6.  However, I have the same issue if I install the module locally and attempt to run with "puppet apply".

I have created the simplest YAML including the domain, user, and password.  However, I always receive the above error.  Has anyone seen this and know how to correct it?  I've tried using --verbose and --trace and don't get any useful information.

**Comment by walkamongus** [comment]
Hi @unixsanet -- can you post some errors or log output?

**Comment by unixsanet** [comment]
`
# puppet apply site.pp --debug
Debug: Executing '/bin/rpm --version'
Debug: Executing '/bin/rpm -ql rpm'
Debug: Executing '/bin/rpm --version'
Info: Loading facts in /etc/puppet/modules/stdlib/lib/facter/pe_version.rb
Info: Loading facts in /etc/puppet/modules/stdlib/lib/facter/facter_dot_d.rb
Info: Loading facts in /etc/puppet/modules/stdlib/lib/facter/package_provider.rb
Info: Loading facts in /etc/puppet/modules/stdlib/lib/facter/service_provider.rb
Info: Loading facts in /etc/puppet/modules/stdlib/lib/facter/puppet_settings.rb
Info: Loading facts in /etc/puppet/modules/stdlib/lib/facter/root_home.rb
Info: Loading facts in /var/lib/puppet/lib/facter/staging_http_get.rb
Info: Loading facts in /var/lib/puppet/lib/facter/ip6tables_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/puppet_settings.rb
Info: Loading facts in /var/lib/puppet/lib/facter/service_provider.rb
Info: Loading facts in /var/lib/puppet/lib/facter/mysql_server_id.rb
Info: Loading facts in /var/lib/puppet/lib/facter/apache_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/staging_windir.rb
Info: Loading facts in /var/lib/puppet/lib/facter/apt_update_last_success.rb
Info: Loading facts in /var/lib/puppet/lib/facter/facter_dot_d.rb
Info: Loading facts in /var/lib/puppet/lib/facter/root_home.rb
Info: Loading facts in /var/lib/puppet/lib/facter/apt_updates.rb
Info: Loading facts in /var/lib/puppet/lib/facter/lvm_support.rb
Info: Loading facts in /var/lib/puppet/lib/facter/package_provider.rb
Info: Loading facts in /var/lib/puppet/lib/facter/vmware.rb
Info: Loading facts in /var/lib/puppet/lib/facter/mysqld_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/pe_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/iptables_persistent_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/iptables_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/puppetgem.rb
Info: Loading facts in /var/lib/puppet/lib/facter/concat_basedir.rb
Info: Loading facts in /var/lib/puppet/lib/facter/gemhome.rb
Info: Loading facts in /var/lib/puppet/lib/facter/mysql_version.rb
Debug: Puppet::Type::Package::ProviderPe_gem: file /opt/puppet/bin/gem does not exist
Debug: Puppet::Type::Package::ProviderAix: file /usr/bin/lslpp does not exist
Debug: Puppet::Type::Package::ProviderDpkg: file /usr/bin/dpkg does not exist
Debug: Puppet::Type::Package::ProviderApt: file /usr/bin/apt-get does not exist
Debug: Puppet::Type::Package::ProviderAptitude: file /usr/bin/aptitude does not exist
Debug: Puppet::Type::Package::ProviderAptrpm: file apt-get does not exist
Debug: Puppet::Type::Package::ProviderSun: file /usr/bin/pkginfo does not exist
Debug: Puppet::Type::Package::ProviderFink: file /sw/bin/fink does not exist
Debug: Puppet::Type::Package::ProviderOpenbsd: file pkg_info does not exist
Debug: Puppet::Type::Package::ProviderFreebsd: file /usr/sbin/pkg_info does not exist
Debug: Puppet::Type::Package::ProviderHpux: file /usr/sbin/swinstall does not exist
Debug: Puppet::Type::Package::ProviderNim: file /usr/sbin/nimclient does not exist
Debug: Puppet::Type::Package::ProviderOpkg: file opkg does not exist
Debug: Puppet::Type::Package::ProviderPacman: file /usr/bin/pacman does not exist
Debug: Puppet::Type::Package::ProviderPkg: file /usr/bin/pkg does not exist
Debug: Puppet::Type::Package::ProviderPkgin: file pkgin does not exist
Debug: Puppet::Type::Package::ProviderPortage: file /usr/bin/emerge does not exist
Debug: Puppet::Type::Package::ProviderPorts: file /usr/local/sbin/portupgrade does not exist
Debug: Puppet::Type::Package::ProviderPortupgrade: file /usr/local/sbin/portupgrade does not exist
Debug: Puppet::Type::Package::ProviderRug: file /usr/bin/rug does not exist
Debug: Puppet::Type::Package::ProviderSunfreeware: file pkg-get does not exist
Debug: Puppet::Type::Package::ProviderUp2date: file /usr/sbin/up2date-nox does not exist
Debug: Puppet::Type::Package::ProviderUrpmi: file urpmi does not exist
Debug: Puppet::Type::Package::ProviderZypper: file /usr/bin/zypper does not exist
Debug: Puppet::Type::Service::ProviderDaemontools: file /usr/bin/svc does not exist
Debug: Puppet::Type::Service::ProviderDebian: file /usr/sbin/update-rc.d does not exist
Debug: Puppet::Type::Service::ProviderGentoo: file /sbin/rc-update does not exist
Debug: Puppet::Type::Service::ProviderLaunchd: file /bin/launchctl does not exist
Debug: Puppet::Type::Service::ProviderOpenrc: file /bin/rc-status does not exist
Debug: Puppet::Type::Service::ProviderRunit: file /usr/bin/sv does not exist
Debug: Puppet::Type::Service::ProviderUpstart: 0 confines (of 2) were true
Debug: importing '/etc/puppet/modules/realmd/manifests/init.pp' in environment production
Debug: Automatically imported realmd from realmd into production
Debug: importing '/etc/puppet/modules/realmd/manifests/params.pp' in environment production
Debug: Automatically imported realmd::params from realmd/params into production
Debug: hiera(): Hiera YAML backend starting
Debug: hiera(): Looking up realmd::realmd_package_name in YAML backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.yaml, skipping
Debug: hiera(): Hiera JSON backend starting
Debug: hiera(): Looking up realmd::realmd_package_name in JSON backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/vratest.corp.local.json, skipping
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.json, skipping
Debug: hiera(): Looking up realmd::realmd_config_file in YAML backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.yaml, skipping
Debug: hiera(): Looking up realmd::realmd_config_file in JSON backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/vratest.corp.local.json, skipping
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.json, skipping
Debug: hiera(): Looking up realmd::realmd_config in YAML backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.yaml, skipping
Debug: hiera(): Looking up realmd::realmd_config in JSON backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/vratest.corp.local.json, skipping
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.json, skipping
Debug: hiera(): Looking up realmd::adcli_package_name in YAML backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.yaml, skipping
Debug: hiera(): Looking up realmd::adcli_package_name in JSON backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/vratest.corp.local.json, skipping
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.json, skipping
Debug: hiera(): Looking up realmd::krb_client_package_name in YAML backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.yaml, skipping
Debug: hiera(): Looking up realmd::krb_client_package_name in JSON backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/vratest.corp.local.json, skipping
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.json, skipping
Debug: hiera(): Looking up realmd::sssd_package_name in YAML backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.yaml, skipping
Debug: hiera(): Looking up realmd::sssd_package_name in JSON backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/vratest.corp.local.json, skipping
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.json, skipping
Debug: hiera(): Looking up realmd::sssd_service_name in YAML backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.yaml, skipping
Debug: hiera(): Looking up realmd::sssd_service_name in JSON backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/vratest.corp.local.json, skipping
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.json, skipping
Debug: hiera(): Looking up realmd::sssd_config_file in YAML backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.yaml, skipping
Debug: hiera(): Looking up realmd::sssd_config_file in JSON backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/vratest.corp.local.json, skipping
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.json, skipping
Debug: hiera(): Looking up realmd::sssd_config_cache_file in YAML backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.yaml, skipping
Debug: hiera(): Looking up realmd::sssd_config_cache_file in JSON backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/vratest.corp.local.json, skipping
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.json, skipping
Debug: hiera(): Looking up realmd::sssd_config in YAML backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.yaml, skipping
Debug: hiera(): Looking up realmd::sssd_config in JSON backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/vratest.corp.local.json, skipping
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.json, skipping
Debug: hiera(): Looking up realmd::manage_sssd_config in YAML backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.yaml, skipping
Debug: hiera(): Looking up realmd::manage_sssd_config in JSON backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/vratest.corp.local.json, skipping
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.json, skipping
Debug: hiera(): Looking up realmd::mkhomedir_package_names in YAML backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.yaml, skipping
Debug: hiera(): Looking up realmd::mkhomedir_package_names in JSON backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/vratest.corp.local.json, skipping
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.json, skipping
Debug: hiera(): Looking up realmd::domain in YAML backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.yaml, skipping
Debug: hiera(): Looking up realmd::domain in JSON backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/vratest.corp.local.json, skipping
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.json, skipping
Debug: hiera(): Looking up realmd::domain_join_user in YAML backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.yaml, skipping
Debug: hiera(): Looking up realmd::domain_join_user in JSON backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/vratest.corp.local.json, skipping
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.json, skipping
Debug: hiera(): Looking up realmd::domain_join_password in YAML backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.yaml, skipping
Debug: hiera(): Looking up realmd::domain_join_password in JSON backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/vratest.corp.local.json, skipping
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.json, skipping
Debug: hiera(): Looking up realmd::krb_ticket_join in YAML backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.yaml, skipping
Debug: hiera(): Looking up realmd::krb_ticket_join in JSON backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/vratest.corp.local.json, skipping
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.json, skipping
Debug: hiera(): Looking up realmd::krb_keytab in YAML backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.yaml, skipping
Debug: hiera(): Looking up realmd::krb_keytab in JSON backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/vratest.corp.local.json, skipping
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.json, skipping
Debug: hiera(): Looking up realmd::krb_config_file in YAML backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.yaml, skipping
Debug: hiera(): Looking up realmd::krb_config_file in JSON backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/vratest.corp.local.json, skipping
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.json, skipping
Debug: hiera(): Looking up realmd::krb_config in YAML backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.yaml, skipping
Debug: hiera(): Looking up realmd::krb_config in JSON backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/vratest.corp.local.json, skipping
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.json, skipping
Debug: hiera(): Looking up realmd::manage_krb_config in YAML backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.yaml, skipping
Debug: hiera(): Looking up realmd::manage_krb_config in JSON backend
Debug: hiera(): Looking for data source vratest.corp.local
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/vratest.corp.local.json, skipping
Debug: hiera(): Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppet/environments/production/hieradata/common.json, skipping
Debug: importing '/etc/puppet/modules/realmd/manifests/install.pp' in environment production
Debug: Automatically imported realmd::install from realmd/install into production
Debug: importing '/etc/puppet/modules/realmd/manifests/config.pp' in environment production
Debug: Automatically imported realmd::config from realmd/config into production
Debug: Scope(Class[Realmd::Config]): Retrieving template realmd/realmd.conf.erb
Debug: template[/etc/puppet/modules/realmd/templates/realmd.conf.erb]: Bound template variables for /etc/puppet/modules/realmd/templates/realmd.conf.erb in 0.00 seconds
Debug: template[/etc/puppet/modules/realmd/templates/realmd.conf.erb]: Interpolated template /etc/puppet/modules/realmd/templates/realmd.conf.erb in 0.00 seconds
Debug: importing '/etc/puppet/modules/realmd/manifests/join.pp' in environment production
Debug: Automatically imported realmd::join from realmd/join into production
Debug: importing '/etc/puppet/modules/realmd/manifests/join/password.pp' in environment production
Debug: Automatically imported realmd::join::password from realmd/join/password into production
Debug: importing '/etc/puppet/modules/realmd/manifests/sssd/config.pp' in environment production
Debug: Automatically imported realmd::sssd::config from realmd/sssd/config into production
Debug: importing '/etc/puppet/modules/realmd/manifests/sssd/service.pp' in environment production
Debug: Automatically imported realmd::sssd::service from realmd/sssd/service into production
Debug: Adding relationship from Class[Realmd::Install] to Class[Realmd::Config] with 'before'
Debug: Adding relationship from Class[Realmd::Config] to Class[Realmd::Join] with 'notify'
Debug: Adding relationship from Class[Realmd::Join] to Class[Realmd::Sssd::Config] with 'before'
Debug: Adding relationship from Class[Realmd::Sssd::Config] to Class[Realmd::Sssd::Service] with 'notify'
Error: undefined method `ref' for nil:NilClass on node vratest.corp.local
Error: undefined method `ref' for nil:NilClass on node vratest.corp.local
`

**Comment by walkamongus** [comment]
@unixsanet were you able to get around this issue? I haven't seen it myself or had any other reports of it yet.

**Comment by walkamongus** [comment]
closing as stale
