### ISSUE TITLE
realmd not creating krb5 keytab

### ISSUE THREAD

**Issue by sidrew** [walkamongus/realmd#16]
Hey...

I was wondering how you got around the "realm join" not creating the krb5 keytab.  I was developing a module that did some of this and found that when I exec the "realm join" that it doesn't create the keytab... but, if I run the same command in the FG... it does.

Thanks,

Andy

**Comment by walkamongus** [comment]
Hi @sidrew are you referring to the keytab used to join a domain in a "password-less join"? Or are you referring to a keytab that the realm command should create after joining using a password?

**Comment by sidrew** [comment]
The latter... I'm doing a join using a password... and for some reason the realm join isn't creating /etc/krb5.keytab like I would expect.  When I run the exact same command manually... it joins perfectly and creates the keytab file... just trying to figure out where it's failing.

Thanks, @walkamongus!

**Comment by walkamongus** [comment]
@sidrew were you able to figure out what the issue is?

**Comment by walkamongus** [comment]
closing as stale issue
