### ISSUE TITLE
hiera config

### ISSUE THREAD

**Issue by pderuiter** [walkamongus/realmd#18]
Hi,
 It would be nice if there was an example config on how to configure this in hiera since this is missing in the documentation

**Comment by michaelsstuff** [comment]
I struggled a bit with it, but got some of it working with hiera and eyaml:
 
`realmd::domain_join_user: 'yourADjoinUser'`
`realmd::domain_join_password:    >
   ENC[PKCS7,SUPERCRYPTEDPASSWORD]`
`realmd::realmd_config:`
`   'users':`
`      default-home: '/home/%U'`
`   'yourdomain.com':`
`      fully-qualified-names: 'no'`

realmd_config is a hashmap
Watch your spaces! yaml is counting leading spaces.

**Comment by walkamongus** [comment]
the data directory now has Hiera data that can be used for examples
