### ISSUE TITLE
Please drop a new version to Puppet Forge for Debian-based distros

### ISSUE THREAD

**Issue by howels** [walkamongus/realmd#22]
Hi,

Stuck looking for an elegant way to configure SSSD again and I came back to your code which I bookmarked a while ago.  Looks like you have no included support for Debian-based distros, would it be possible to release a new version as the content on Puppet Forge states that only RHEL-based distros are supported. 

Thanks

**Comment by walkamongus** [comment]
Hi @howels is is the realmd tool available on Debian systems? Take a look at my SSSD module at https://github.com/walkamongus/sssd/tree/puppet_4_overhaul. I just did an overhaul for Puppet 4 and I'll be releasing it to the Forge soon.

**Comment by howels** [comment]
Both realmd and SSSD are now available in Debian (https://packages.debian.org/jessie/admin/realmd) and Ubuntu (https://packages.ubuntu.com/xenial/realmd).

I'm looking to join an AD domain automatically so while SSSD is a useful component realmd is essential in order to create the computer account in AD.  I've verified that this works well in CentOS 7 and it looks like there are sufficient packages for it to work on Jessie or Xenial also now.

**Comment by rsynnest** [comment]
@howels I've tested https://forge.puppet.com/acjohnson/adcli/scores and it is working for me on Ubuntu 16.04 to join a computer to a domain.
I still haven't been able to get user authentication working, but I'm pretty new to AD for Linux. I'm not sure if samba or krb5-user or something else is needed besides adcli + sssd.

**Comment by walkamongus** [comment]
Just to follow-up -- I'd gladly accept PRs to support Debian-based distros or update the metadata if everything works as-is. I just am not currently using any Debian-based systems so I haven't tested it with them.

**Comment by walkamongus** [comment]
#23 should fix -- released to Forge as v1.0.0
