### ISSUE TITLE
Path /usr/libexec/ doesn't exist on Ubuntu

### ISSUE THREAD

**Issue by jmswick** [walkamongus/realmd#31]
With the recent merge of #29, I'm getting errors from the module on my Ubuntu test system, due to the path /usr/libexec not existing there, I haven't checked on a Debian system, but I suspect it would be the same there.

```
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_mkdir - /usr/libexec/realm_join_with_password20170719-11402-1xrte2l.lock at /etc/puppetlabs/code/environments/realm_patch/modules/realmd/manifests/join/password.pp:21
```

Using /usr/local/bin might be better, but may not be LSB compliant.

**Comment by rsynnest** [comment]
I'm getting the same error on Ubuntu 16.04
I'll refrain from casting a vote for which directory to use, but it's good to be aware that `/usr/libexec` is an optional directory according to the Linux FHS, meaning it might not exist and needs to be ensured before placing files there. `/usr/local/bin` on the other hand is a required directory which exists on all FHS compliant distros so shouldn't need to be ensured.

Both Debian and RedHat follow [FHS 2.3](http://www.pathname.com/fhs/)

**Comment by ms1111** [comment]
FWIW, I'm able to use an old commit, 8d1a3adf1a9b82b64bc19263c849daee5b4e79a8, on Ubuntu 16.04. This is somewhere between v0.1.3 and v1.0.0.

v1.0.0+ is broken on Ubuntu because of the /usr/libexec thing.

**Comment by walkamongus** [comment]
This is a quick fix if anyone wants to put in a PR, but I'm in the middle of moving so it might be a little while until I can get to it.
