### ISSUE TITLE
params.pp is missing in version 2.1.0

### ISSUE THREAD

**Issue by dstaskiewicz-vervint** [walkamongus/realmd#34]
After extracting walkamongus-realmd-2.1.0.tar.gz the file manifests/params.pp is missing.

**Comment by walkamongus** [comment]
Version 2.x dropped support for Puppet 3 and has been converted to use data-in-modules instead of the params.pp pattern. See the full changlog at https://github.com/walkamongus/realmd/compare/v1.0.0...v2.0.0 for more info.
