### ISSUE TITLE
join with password, OU prefix

### ISSUE THREAD

**Issue by acurus-puppetmaster** [walkamongus/realmd#39]
When you join with a password and provide an OU to place the computer object in the format of the OU string isn't what we would normally expect when dealing with Active Directory.

The AD distinguished name begins with OU=

Which we record in Hiera as

`ad_ou: 'OU=Linux,OU=ISP,OU=Internal Systems,DC=services,DC=company,DC=com'`

But the module already adds the OU=

Which means the actual OU specifed in the end becomes
`OU=OU=Linux,OU=ISP,OU=Internal Systems,DC=services,DC=company,DC=com`

Which fails.

It would be great if this was not added as a prefix.

**Comment by acurus-puppetmaster** [comment]
Submitted pull request #40

**Comment by acurus-puppetmaster** [comment]
Almost a year and no traction on this PR.

**Comment by walkamongus** [comment]
Hi @acurus-puppetmaster  -- if you check the PR, it was merged back on June 16th.

**Comment by acurus-puppetmaster** [comment]
But the last release you did was in 2017.  so those of us who like to use the forge released version can't access any recent changes.

**Comment by walkamongus** [comment]
Ok...thanks for clarifying. I'll try to push a new Forge release later today or tomorrow at the latest. I'll close this once the new Forge release is available.

**Comment by acurus-puppetmaster** [comment]
Excellent news, thank you.

**Comment by walkamongus** [comment]
v2.3.0 is up now on the Forge
