### ISSUE TITLE
Package[krb5-workstation] is already declared

### ISSUE THREAD

**Issue by netsur0** [walkamongus/realmd#4]
Hi,

i have this error : 
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Package[krb5-workstation] is already declared; cannot redeclare at /etc/puppet/environments/production/modules/realmd/manifests/install.pp:17 on node

it was already installed with mit_krb5 module.

**Comment by andrewwippler** [comment]
Then it is obvious - this realmd module is incompatible with the mit_krb5 module. Choose the module that best fits your environment for managing krb authentication and stick with that. As for this issue, it really isn't one.

**Comment by walkamongus** [comment]
closing -- as mentioned, only one module should be chosen to manage krb configuration
