### ISSUE TITLE
Ubuntu 16.04: Unknown Option --computer-name

### ISSUE THREAD

**Issue by adrianmace** [walkamongus/realmd#43]
When running this with a fairly simple password-based implementation of realmd I have the following error returned to me on the screen. Commit: cd67f01
```
Notice: /Stage[main]/Realmd::Join::Password/Exec[realm_join_with_password]/returns: realm: Unknown option --computer-name=ME0P999-MIKE
Error: '/usr/libexec/realm_join_with_password realm join in.bill.com.au --unattended --user=svc_puppetjoiner --computer-name=ME0P999-MIKE' returned 2 instead of one of [0]
Error: /Stage[main]/Realmd::Join::Password/Exec[realm_join_with_password]/returns: change from 'notrun' to ['0'] failed: '/usr/libexec/realm_join_with_password realm join in.bill.com.au --unattended --user=puppet --computer-name=ME0P999-MIKE' returned 2 instead of one of [0]
```

**Comment by adrianmace** [comment]
The manpages for ubuntu 16.04 seems to indicate that the --computer-name option is not defined in the version of realm preinstalled. Can this issue please be revised to be considered an enhancement that will bring ubuntu support to the module?

Regards

**Comment by walkamongus** [comment]
I'll have to rely on the community to add this support as I don't currently use Ubuntu.

**Comment by adrianmace** [comment]
Happy to test this for you if changes are committed. It's also possible to test this quite efficiently with Docker if you already have the domain infrastructure.

**Comment by Romiko** [comment]
I can confirm this is an issue with my ubuntu version as well.
--computer-name  is not an option.

**Comment by Romiko** [comment]
I will fork this repo and see if I can fix this.

**Comment by Romiko** [comment]
I have created a Pull Request with the fix @adrianmace @walkamongus.
 
The module now works on Ubuntu 16.04

**Comment by adrianmace** [comment]
Thank you @Romiko :) I will make sure to use it once it's merged and report back.

**Comment by Romiko** [comment]
Hey

You can use my fork for now

I wrote a blog about this here

https://romikoderbynew.com/2018/09/15/puppet-join-ubuntu-16-04-servers-to-an-azure-windows-active-directory-domain/


mod 'romiko-realmd',
  :git    => 'https://github.com/Romiko/realmd.git',
  :branch => 'master'

**Comment by walkamongus** [comment]
Merged -- thanks @Romiko!
