### ISSUE TITLE
Ubuntu 14.04 and Puppet 3.8

### ISSUE THREAD

**Issue by obenziane21** [walkamongus/realmd#44]
Is it possible to use this module with Ubuntu 14.04 and Puppet 3.8 ? Any older version that might work in this case ?

Thanks

**Comment by walkamongus** [comment]
Hi @obenziane21 I doubt it will work on Puppet 3.x, but I haven't tested on this older version or on Ubuntu.

**Comment by obenziane21** [comment]
thanks @walkamongus
