### ISSUE TITLE
Realmd is not available on Red Hat family 6 and older

### ISSUE THREAD

**Issue by bschonec** [walkamongus/realmd#47]
https://access.redhat.com/solutions/2273711

realmd is not available on anything older than version 7.  I would be nice to put in a check for the major OS release < 7 or (preferable) add the ability to use this module with the use of 'adcli' instead of 'realm' for joining Active Directory.

**Comment by tux-o-matic** [comment]
Or use the adcli module together with sssd on EL 6 systems. 
You can use OS Facts in Hiera or site.pp for your node classification.

**Comment by SohamChakraborty** [comment]
@tux-o-matic which adcli module do you use?

**Comment by tux-o-matic** [comment]
@SohamChakraborty https://forge.puppet.com/acjohnson/adcli

**Comment by SohamChakraborty** [comment]
Thank you @tux-o-matic

**Comment by walkamongus** [comment]
closing issue as adcli module seems like the best answer
