### ISSUE TITLE
Duplicate declaration: Packages adcli and sssd are already declared.

### ISSUE THREAD

**Issue by utking** [walkamongus/realmd#49]
Hello,
Suddenly, I got the following error:

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Duplicate declaration: Package[adcli] is already declared in file /etc/puppetlabs/code/environments/production/modules/realmd/manifests/install.pp:11; cannot redeclare at /etc/puppetlabs/code/environments/production/modules/realmd/manifests/install.pp:23 at /etc/puppetlabs/code/environments/production/modules/realmd/manifests/install.pp:23:3 at /etc/puppetlabs/code/environments/production/modules/realmd/manifests/init.pp:60 on node test-host.domain.loc`

It seems to be because of the install.pp manifest ensuring separate packages (including sssd and adcli) and then trying to ensure part of them (sssd and adcli) again using ensure_packages for several packages from the yaml files.

**Comment by walkamongus** [comment]
#51 should resolve this
