### ISSUE TITLE
No RHEL6 Support

### ISSUE THREAD

**Issue by Tvaske** [walkamongus/realmd#5]
After reviewing this module i have determined with little effort it could support RHEL6, i am willing to make those additions. If i sent you a PR would you agree that it fits in this module?

**Comment by walkamongus** [comment]
Hi -- pull requests are most welcome! I'd just ask that you submit passing tests in addition to the new feature.  Thanks!

**Comment by brettswift** [comment]
@Tvaske would love to see this as well.  If you have some early preview stuff and want me to test / contribute just let me know.

**Comment by Tvaske** [comment]
We went down a different road for this one, since realmd is not a package that is available for RHEL6 we decided to use the SSSD module and use this module https://forge.puppet.com/acjohnson/adcli to join the AD domain. Thanks @acjohnson!!

**Comment by walkamongus** [comment]
Thanks @Tvaske for reporting this! Closing as a lack of realmd package seems like a showstopper for RHEL 6 support.
