### ISSUE TITLE
Module shouldn't enforce sssd service state

### ISSUE THREAD

**Issue by tux-o-matic** [walkamongus/realmd#59]
Some environments need a separate sssd module and this creates a duplicate resource problem.
Since this module is named "realmd", it shouldn't enforce a state for the sssd module.
Just like there is a *manage_sssd_config* boolean flag, there could be a *manage_sssd_service*.

**Comment by walkamongus** [comment]
Hi @tux-o-matic -- this sounds like a reasonable parameter for flexibility. It might take a while to get this added, but PRs are always welcome!
