### ISSUE TITLE
sssd.conf template in the wrong place?

### ISSUE THREAD

**Issue by gilbo47** [walkamongus/realmd#60]
Run of module gives:

 Evaluation Error: Error while evaluating a Function Call, Could not find template 'sssd/sssd.conf.erb' (file: ...../modules/sssd/manifests/init.pp, line: 185, column: 16) on node <nodename>

**Comment by gilbo47** [comment]
Appears the module has moved on from the latest tag.  referenced via commit ID and it fixed.

**Comment by walkamongus** [comment]
This will be included in the next release to the Forge.
