### ISSUE TITLE
one-time-password join uses ADCLI instead of realm?

### ISSUE THREAD

**Issue by LIV2** [walkamongus/realmd#62]
https://github.com/walkamongus/realmd/blob/c1007e50cec37cc088ea637eb867da69727f891d/manifests/join/one_time_password.pp#L76

Joining with adcli doesn't configure SSSD etc while using the realm command does, is there a reason why the adcli should command be used here instead of realm?

**Comment by walkamongus** [comment]
This was added in #42  -- I don't have this particular use case so I'm not sure, but I'm open to any better solution if it fits the use-case.

**Comment by LIV2** [comment]
ah okay that answers my question, thanks :)
