### ISSUE TITLE
Module is not idempotent when hostname is longer than 15 characters.

### ISSUE THREAD

**Issue by serialh0bbyist** [walkamongus/realmd#7]
If the hostname is longer than 15 characters the following `unless` statements becomes invalid: https://github.com/walkamongus/realmd/blob/master/manifests/join/password.pp#L15 https://github.com/walkamongus/realmd/blob/master/manifests/join/keytab.pp#L45. Pull request on the way...

**Comment by walkamongus** [comment]
fix merged -- thanks!
